export const text = {
  nav: {
    home: "Home",
    about: "About Us",
    howWeWork: "How We Work",
    ourWorks: "Our Works",
    news: "News",
    faq: "FAQ",
    contact: "Contact",
    getQuote: "Get A Quote",
  },
  hero: {
    label: "Engineering · Design · Construction",
    h1: "Building Your Dream Home, One Brick at a Time",
    subtitle: "From concept to completion — Horizon Nepal delivers quality home construction, bespoke interior design, and reliable material cost consultation across Nepal.",
    cta: "Get Started",
    cta2: "View Projects",
  },
  services: {
    label: "Our Services",
    h2: "What We Build & Design",
    subtitle: "Focused expertise in residential construction, interior design, and construction material consultation across Nepal.",
    explore: "Explore More",
    cards: [
      {
        icon: "Home",
        title: "House Construction",
        body: "End-to-end residential construction services — from foundation to finishing. We build homes that are safe, durable, and tailored to your family's needs and Nepal's unique terrain.",
      },
      {
        icon: "Compass",
        title: "Interior Design",
        body: "Complete interior design solutions for homes and offices. Space planning, material selection, furniture design, and fit-out — creating spaces you'll love to live and work in.",
      },
      {
        icon: "PenTool",
        title: "Material Cost Consultation",
        body: "Transparent pricing and sourcing for construction materials — from aggregates and cement to finishes. We help you plan your budget with accurate, up-to-date quarry and supplier rates.",
      },
      {
        icon: "Users",
        title: "Site Visit & Feasibility",
        body: "On-site assessment of land, structure, and surroundings before you build. Our engineers evaluate feasibility, soil conditions, access, and provide clear recommendations for your project.",
      },
    ],
  },
  process: {
    label: "How We Work",
    h2: "Building Your Home in 3 Simple Steps",
    subtitle: "A transparent, milestone-based process built around your peace of mind — from first conversation to keys in hand.",
    simpleSteps: "simple steps",
    steps: [
      {
        title: "Share Your Plan",
        body: "Tell us your vision, budget and timeline. We listen, ask sharp questions, and confirm fit before any commitment.",
      },
      {
        title: "Design & Planning",
        body: "Our architects produce blueprints, 3D renders, BoQ, and permit-ready documents for your review and approval.",
      },
      {
        title: "Build & Handover",
        body: "Expert teams execute on-site with weekly client updates, third-party inspections, and a clean final handover.",
      },
    ],
  },
  portfolio: {
    label: "Our Portfolio",
    h2: "Explore Our Works",
    viewAll: "View All Projects",
    viewProject: "View Project",
  },
  about: {
    label: "About Us",
    h2: "Horizon Nepal — Built for Generations",
    description: "With years of combined leadership, Horizon Nepal delivers quality homes, thoughtful interiors, and reliable construction consultation services across the country.",
    stats: [
      { value: "30+", label: "Years of Collective Experience" },
      { value: "200+", label: "Projects Completed" },
      { value: "50+", label: "Expert Team Members" },
      { value: "15+", label: "Districts Served" },
    ],
    approachLabel: "Our Approach",
    storyTitle: "Our Story",
    story1: "Founded on the belief that every family deserves a safe, beautiful home, Horizon Nepal brings together engineering excellence, design sensitivity, and transparent business practices. We don't just build structures — we build trust, one project at a time.",
    story2: "From house construction to interior fit-outs, from material cost estimates to site assessments — we invest in the latest 3D modelling tools and rigorous quality checks so that precision is part of every decision.",
    valuesLabel: "What We Stand For",
    valuesTitle: "Our Core Values",
    values: [
      {
        title: "Quality Craftsmanship",
        body: "We use only the best materials and employ skilled craftsmen who take pride in their work. Every joint, finish, and detail meets our exacting standards.",
      },
      {
        title: "Innovative Design",
        body: "Our designers push boundaries while respecting Nepal's unique terrain, climate, and culture. Every home is designed to be functional, beautiful, and sustainable.",
      },
      {
        title: "Integrity & Transparency",
        body: "Fixed-price contracts, detailed BoQ, regular progress updates — no surprises, just honest work delivered as promised.",
      },
      {
        title: "Client-Centric Approach",
        body: "Your vision drives everything we do. From the first site visit to the final walkthrough, you are at the centre of the process.",
      },
    ],
    cta: "Explore Our Works",
  },
  welcome: {
    label: "Welcome to Horizon Nepal",
    h2: "Your Vision, Our Craft",
    body: "We believe in transparency, craftsmanship, and collaboration. This page walks you through exactly how we work — from your first idea to the moment you step inside your completed space. No jargon, no hidden steps — just a clear partnership built around your vision.",
  },
  howWeWork: {
    meta: {
      title: "How We Work — Horizon Nepal Construction Process",
      description: "From your first consultation to final handover — discover Horizon Nepal's 7-step construction process.",
      keywords: [
        "construction process Nepal", "building design Kathmandu",
        "architectural services Nepal", "how construction works",
        "Horizon Nepal process", "Nepal construction company",
        "residential building process", "commercial construction Nepal",
      ],
      ogTitle: "How We Work | Horizon Nepal",
      ogDescription: "A transparent 7-step journey from first hello to final handover.",
    },
    faqLoading: "Loading FAQ...",
    hero: {
      label: "Start Your Journey",
      h1a: "How We Transform Your Vision",
      h1b: "Into Reality",
      subtitle: "A transparent, collaborative journey from your first hello to your final handover. No surprises — just expert guidance at every step.",
      cta: "See Our Process",
      cta2: "Book a Consultation",
    },
    process: {
      label: "Our Process",
      h2: "From First Hello to Final Handover",
      subtitle: "Seven steps designed to make your construction journey smooth, transparent, and stress-free.",
    simpleSteps: "simple steps",
    steps: [
        {
          title: "Welcome & Discovery",
          body: "We start with a warm welcome. Tell us about your project, your vision, and your goals. We listen carefully to understand what matters most to you.",
        },
        {
          title: "Share Your Vision",
          body: "Share your ideas, references, sketches, or any inspiration. Our team reviews your requirements and outlines the best approach for your project.",
        },
        {
          title: "Site Visit & Assessment",
          body: "We visit your site to assess the land, surroundings, and feasibility. Our engineers take measurements, note challenges, and identify opportunities.",
        },
        {
          title: "Design & Planning",
          body: "Our architects create detailed designs, 3D renderings, and structural plans. You receive blueprints, BoQ, and permit-ready documents for review.",
        },
        {
          title: "Review & Approve",
          body: "You review every detail of the design. We make revisions until you are 100% satisfied. Once approved, we move to construction with your signed go-ahead.",
        },
        {
          title: "Build & Monitor",
          body: "Our expert teams execute on-site with precision. You get weekly progress updates, photos, and milestone reports. Watch your project come to life.",
        },
        {
          title: "Handover & Celebrate",
          body: "We conduct a final walkthrough, address any punch-list items, and hand over the keys. Your dream is now reality — built to last for generations.",
        },
      ],
    },
    designGrid: {
      label: "Design Perspectives",
      h2: "Every Angle Considered",
      subtitle: "We don't just design facades — we design experiences. Here is how we approach each perspective of your project.",
      perspectives: [
        {
          num: "01",
          label: "Front Elevation",
          title: "The Face of Your Building",
          body: "Every structure tells a story from the street. We craft front elevations that respect the neighbourhood character while creating a lasting first impression that complements its surroundings.",
        },
        {
          num: "02",
          label: "Rear Perspective",
          title: "Where Function Meets Nature",
          body: "The rear of a building is where indoor living meets outdoor comfort. We design back facades with thoughtful transitions — courtyards, terraces, and gardens that turn the back of your home into a private sanctuary.",
        },
        {
          num: "03",
          label: "Top-Down Layout",
          title: "The Blueprint of Flow",
          body: "A great home starts with an intelligent floor plan. Every room is positioned for natural light, cross-ventilation, and smooth circulation — making daily life effortless while maintaining an open, breathable atmosphere.",
        },
        {
          num: "04",
          label: "Interior Angle",
          title: "Spaces You Feel",
          body: "Interior design is about more than finishes. We layer textures, light, and proportion to create rooms that feel right. Every material, colour, and furnishing choice guides you naturally from one space to the next.",
        },
        {
          num: "05",
          label: "Side Profile",
          title: "Silhouette & Substance",
          body: "A building's side profile reveals its structural rhythm. We balance mass, void, and roofline to create a confident, grounded presence that feels as solid as it looks.",
        },
      ],
    },
    designViews: {
      label: "Design Showcase",
      h2: "See Your Home Come to Life Before We Build",
      subtitle: "Explore interactive 3D architectural designs and interior walkthroughs — all created before a single brick is laid.",
      archLabel: "Architectural Design",
      archTitle: "Interactive 3D Model",
      archBody: "Explore every detail of your home in real time. Rotate, zoom, and inspect the design from every angle before construction begins.",
      interiorLabel: "Interior Design",
      interiorTitle: "Design Walkthrough",
      interiorBody: "Step inside your future space with detailed interior visualizations that capture every finish, texture, and layout decision.",
    },
  },
  news: {
    label: "Latest Updates",
    h2: "Read Our Latest Articles",
    readMore: "Read More",
    viewAll: "View All News",
    back: "Back to News",
    notFound: "Article Not Found",
  },
  faq: {
    label: "FAQ",
    h2: "Answers to Your Construction Questions",
    subtitle: "Everything you need to know about working with Horizon Nepal — from first call to final inspection.",
    ask: "Ask Us Anything",
    viewAll: "View All FAQs",
    filterAll: "All",
  },
  testimonials: {
    label: "Client Stories",
    h2: "What Our Customers Are Saying",
    prev: "Previous testimonial",
    next: "Next testimonial",
  },
  team: {
    label: "Our Team",
    h2: "Meet the Team of Experts",
    subtitle: "Learn about our elite construction advisement team — architects, engineers, and project leaders.",
  },
  consultation: {
    label: "Book A Consultation",
    h2: "Schedule a Smooth and Stress-Free Consultation",
    subtitle: "Our experts are available Monday–Saturday, 9 AM–6 PM NPT. No pitch decks — just a real conversation about your project.",
    formTitle: "Book Your Free Consultation",
    nameLabel: "Full Name *",
    emailLabel: "Email Address *",
    phoneLabel: "Phone Number *",
    phonePlaceholder: "+977 ...",
    serviceLabel: "Service Type *",
    serviceDefault: "Choose a service…",
    serviceOptions: ["House Construction", "Interior Design", "Material Cost Consultation", "Site Visit & Assessment", "Other"],
    descLabel: "Project Description *",
    dateLabel: "Preferred Date *",
    submit: "Schedule My Consultation",
    submitting: "Sending…",
    privacy: "We respect your privacy. Your details are never shared.",
    errors: {
      name: "Please enter your name",
      email: "Enter a valid email",
      phone: "Enter a valid phone number",
      service: "Select a service",
      desc: "Tell us a bit more (10+ chars)",
      date: "Choose a date",
    },
    apiError: "Something went wrong. Please try again.",
    networkError: "Network error. Please check your connection and try again.",
  },
  projectDetail: {
    overview: "Overview",
    video: "Project Video",
    tour: "3D Tour",
    client: "Client",
    name: "Name",
    profession: "Profession",
    earning: "Earning",
    specifications: "Specifications",
    timeline: "Timeline",
    additional3d: "Additional 3D Views",
    moreVideos: "More Videos",
    media: "Media",
    faq: "FAQ",
    filterAll: "All",
    related: "Related Projects",
    previous: "Previous",
    next: "Next",
    ctaHeading: "Build Something Similar",
    ctaSubtitle: "Have a project in mind? Let's discuss how we can bring your vision to life.",
    ctaPrimary: "Start Your Project",
    ctaSecondary: "View All Projects",
    backToPortfolio: "Back to Portfolio",
    viewProject: "View Project Details",
    viewFullProject: "View Full Project Details",
  },
  location: {
    heading: "Horizon Nepal HQ",
    address: "Tinkune, Kathmandu 44600",
    phone: "+977 1 441 1222",
    hours: "Mon–Sat · 9 AM – 6 PM",
    directions: "Get Directions",
  },
  footer: {
    description: "Quality home construction, interior design, and material cost consultation serving Nepal with precision and care.",
    quickLinks: "Quick Links",
    services: "Services",
    contact: "Contact",
    home: "Home",
    about: "About",
    portfolio: "Portfolio",
    houseConstruction: "House Construction",
    interiorDesign: "Interior Design",
    materialConsultation: "Material Cost Consultation",
    siteVisit: "Site Visit & Feasibility",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    copyright: "All rights reserved.",
  },
  statusLabels: {
    planning: "Planning",
    inProgress: "In Progress",
    completed: "Completed",
    onHold: "On Hold",
  },
  listing: {
    news: {
      title: "All News Articles — Horizon Nepal",
      description: "Browse all news articles from Horizon Nepal — home construction updates, interior design insights, and construction tips for Nepal.",
      label: "Stay Informed",
      heading: "All News Articles",
      subtitle: "Read the latest updates, insights, and stories from the Horizon Nepal team — covering construction, design, engineering, and more.",
      empty: "No articles yet. Check back soon!",
      page: "Page",
      of: "of",
      items: [
        { id: "n1", title: "How Earthquake-Resilient Design Is Reshaping Kathmandu Housing", slug: "earthquake-resilient-design-kathmandu", excerpt: "New building codes and innovative engineering techniques are transforming how homes are built in Nepal's most earthquake-prone regions.", category: "Engineering", image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=900&q=80", publishedAt: "2025-11-15" },
        { id: "n2", title: "Inside Our Net-Zero Office Tower Pilot in New Baneshwor", slug: "net-zero-office-tower-baneshwor", excerpt: "A behind-the-scenes look at Kathmandu's first net-zero commercial building and the technology powering its energy independence.", category: "Sustainability", image: "https://images.unsplash.com/photo-1473445730015-841f29a9490b?auto=format&fit=crop&w=900&q=80", publishedAt: "2025-10-28" },
        { id: "n3", title: "Why Local Materials Matter: A Field Report from Pokhara", slug: "local-materials-pokhara-field-report", excerpt: "Our team explores the benefits of sourcing stone, timber and clay from local suppliers for a villa project in Pokhara.", category: "Field Notes", image: "https://images.unsplash.com/photo-1581094271901-8022df4466f9?auto=format&fit=crop&w=900&q=80", publishedAt: "2025-10-10" },
        { id: "n4", title: "5 Interior Design Trends Shaping Nepali Homes in 2025", slug: "interior-design-trends-nepal-2025", excerpt: "From biophilic design to modular kitchens — discover the trends that are redefining how Nepali families live and entertain.", category: "Design", image: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=900&q=80", publishedAt: "2025-09-22" },
        { id: "n5", title: "A Complete Guide to Construction Permits in Kathmandu Valley", slug: "construction-permits-kathmandu-guide", excerpt: "Navigating the permit process can be daunting. We break down every step from application to approval.", category: "Guide", image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=80", publishedAt: "2025-09-05" },
        { id: "n6", title: "Building on a Slope: Engineering Challenges and Solutions", slug: "building-on-slope-engineering", excerpt: "Steep terrain doesn't mean you can't build your dream home. Learn about the engineering techniques that make hillside construction possible.", category: "Engineering", image: "https://images.unsplash.com/photo-1541888946425-d81bb9f3e9b3?auto=format&fit=crop&w=900&q=80", publishedAt: "2025-08-18" },
      ],
    },
    projects: {
      title: "Our Portfolio — Horizon Nepal",
      description: "Browse our complete portfolio of house construction, interior design, and consultation projects across Nepal.",
      label: "Our Portfolio",
      heading: "All Projects",
      subtitle: "Explore our completed and ongoing projects across Nepal — from residential villas to commercial towers and infrastructure.",
      filterAll: "All",
      empty: "No projects found.",
      page: "Page",
      of: "of",
      items: [
        { id: "p1", title: "Sunrise Residential Complex", slug: "sunrise-residential-complex", location: "Lalitpur, Nepal", img: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=900&q=80", alt: "Modern residential complex", status: "completed", completion: 100, budget: 2500000, shortDescription: "A 24-unit modern residential complex with green spaces, rooftop gardens, and earthquake-resistant design.", category: { name: "Residential" } },
        { id: "p2", title: "Araniko Highway Maintenance", slug: "araniko-highway-maintenance", location: "Bhaktapur, Nepal", img: "https://images.unsplash.com/photo-1545972154-9bb223aac798?auto=format&fit=crop&w=900&q=80", alt: "Highway construction", status: "in_progress", completion: 65, budget: 5500000, shortDescription: "Ongoing maintenance and widening of a major highway corridor connecting Bhaktapur to the eastern region.", category: { name: "Road Works" } },
        { id: "p3", title: "New Baneshwor Office Tower", slug: "new-baneshwor-office-tower", location: "Kathmandu, Nepal", img: "https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=900&q=80", alt: "Modern office tower", status: "in_progress", completion: 40, budget: 8000000, shortDescription: "A 12-storey commercial office tower with net-zero energy features and smart building technology.", category: { name: "Commercial" } },
        { id: "p4", title: "Boutique Hotel Interiors", slug: "boutique-hotel-interiors", location: "Thamel, Kathmandu", img: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=900&q=80", alt: "Luxury hotel interior", status: "completed", completion: 100, budget: 1800000, shortDescription: "Complete interior design and fit-out for a 20-room boutique hotel blending Nepali craftsmanship with modern luxury.", category: { name: "Interiors" } },
        { id: "p5", title: "Patan Heritage Renovation", slug: "patan-heritage-renovation", location: "Patan, Nepal", img: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=900&q=80", alt: "Heritage building restoration", status: "planning", completion: 0, budget: 3200000, shortDescription: "Sensitive restoration of a historic Patan courtyard palace into a cultural centre and museum.", category: { name: "Renovation" } },
        { id: "p6", title: "Bagmati Bridge Upgrade", slug: "bagmati-bridge-upgrade", location: "Kathmandu, Nepal", img: "https://images.unsplash.com/photo-1517089596392-fb9a9033e05b?auto=format&fit=crop&w=900&q=80", alt: "Bridge construction", status: "on_hold", completion: 30, budget: 4200000, shortDescription: "Structural upgrade and seismic retrofitting of a key bridge over the Bagmati river.", category: { name: "Road Works" } },
        { id: "p7", title: "Pokhara Lakeside Villa", slug: "pokhara-lakeside-villa", location: "Pokhara, Nepal", img: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80", alt: "Lake view villa", status: "completed", completion: 100, budget: 950000, shortDescription: "A custom-designed lakeside villa with panoramic Himalayan views, outdoor terraces, and sustainable materials.", category: { name: "Residential" } },
        { id: "p8", title: "Chitwan Eco Resort", slug: "chitwan-eco-resort", location: "Chitwan, Nepal", img: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=900&q=80", alt: "Eco resort design", status: "planning", completion: 15, budget: 2800000, shortDescription: "Eco-friendly resort development using local materials, solar energy, and rainwater harvesting systems.", category: { name: "Commercial" } },
      ],
    },
    faq: {
      title: "Frequently Asked Questions — Horizon Nepal",
      description: "Find answers to common questions about house construction, interior design, material costs, and site visits in Nepal.",
      label: "FAQ",
      heading: "Frequently Asked Questions",
      subtitle: "Everything you need to know about working with Horizon Nepal — from first consultation to final handover and beyond.",
      empty: "No FAQs yet.",
      types: [
        { id: "ft1", name: "General", slug: "general" },
        { id: "ft2", name: "Technical", slug: "technical" },
        { id: "ft3", name: "Pricing", slug: "pricing" },
        { id: "ft4", name: "Process", slug: "process" },
      ],
      items: [
        { id: "f1", question: "What types of projects does Horizon Nepal handle?", answer: "We specialise in residential house construction, interior design, material cost consultation, and site feasibility assessments. From single-family homes to multi-unit complexes, our team has the expertise to deliver quality results across a wide range of project sizes and scopes.", faqType: { id: "ft1", name: "General", slug: "general" } },
        { id: "f2", question: "How long does a typical construction project take?", answer: "Timelines vary depending on the size and complexity of the project. A standard single-family home typically takes 8–14 months from ground-breaking to handover. We provide a detailed milestone schedule during the planning phase and keep you updated throughout the build.", faqType: { id: "ft4", name: "Process", slug: "process" } },
        { id: "f3", question: "Do you handle all permits and government approvals?", answer: "Yes. We manage the entire permit and approval process on your behalf, including building permits, environmental clearances, and municipal approvals. Our team is well-versed in Kathmandu Valley's regulatory requirements and ensures all documentation is in order.", faqType: { id: "ft4", name: "Process", slug: "process" } },
        { id: "f4", question: "What makes Horizon Nepal different from other construction companies?", answer: "We combine engineering excellence with design sensitivity and transparent business practices. Every project includes a detailed Bill of Quantities (BoQ), fixed-price contracts, regular progress updates, and third-party quality inspections. We don't just build structures — we build trust.", faqType: { id: "ft1", name: "General", slug: "general" } },
        { id: "f5", question: "How do I get started with a project consultation?", answer: "Simply book a free consultation through our website or call us directly. We'll visit your site, discuss your vision, assess feasibility, and provide a clear outline of next steps — all without any obligation. If we're a good fit, we'll prepare a detailed proposal.", faqType: { id: "ft4", name: "Process", slug: "process" } },
        { id: "f6", question: "What materials do you recommend for construction in Nepal?", answer: "We recommend a combination of locally sourced materials (stone, brick, timber) and modern alternatives (reinforced concrete, structural steel) based on your project's requirements, budget, and location. Our material cost consultation service provides transparent pricing from trusted suppliers.", faqType: { id: "ft2", name: "Technical", slug: "technical" } },
        { id: "f7", question: "How do you ensure quality control during construction?", answer: "Quality is embedded in every phase. We use third-party material testing, regular structural inspections, milestone-based sign-offs, and a dedicated project supervisor on-site. Our teams follow strict safety protocols and maintain detailed progress documentation.", faqType: { id: "ft2", name: "Technical", slug: "technical" } },
        { id: "f8", question: "Can I make changes to the design after construction starts?", answer: "Yes, but changes may affect the timeline and budget. We recommend finalising all design decisions before breaking ground. If changes are needed mid-build, we assess the impact, provide a revised cost estimate, and proceed only with your written approval.", faqType: { id: "ft3", name: "Pricing", slug: "pricing" } },
        { id: "f9", question: "What is included in your interior design service?", answer: "Our interior design service covers space planning, material and finish selection, furniture design, lighting layout, kitchen and bathroom design, and project management. We work closely with you to create spaces that reflect your personality and lifestyle.", faqType: { id: "ft1", name: "General", slug: "general" } },
        { id: "f10", question: "Do you offer post-construction support or maintenance?", answer: "Yes. We provide a structural warranty and offer post- handover support for any issues that arise. Our maintenance services include plumbing, electrical, waterproofing, and general repairs to keep your home in excellent condition for years to come.", faqType: { id: "ft1", name: "General", slug: "general" } },
      ],
    },
  },
  quoteBannerSecondary: {
    text: "We don't just build structures — we build the streets, schools and homes that our grandchildren will live in.",
    attr: "Horizon Nepal Leadership",
  },
  quotes: [
    {
      text: "At the core of our practice is the idea that cities are the incubators of our greatest achievements, and the best hope for a sustainable future.",
      attr: "Horizon Nepal · Core Philosophy",
    },
    {
      text: "Every structure we build is a quiet promise to the generation that will inherit it.",
      attr: "Arun Thapa · Lead Architect",
    },
    {
      text: "We measure success not by what we deliver, but by how it endures.",
      attr: "Priya Shrestha · Project Director",
    },
  ],
  errors: {
    title: "Something went wrong",
    default: "An unexpected error occurred. Please try again.",
    retry: "Try Again",
  },
};
